config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :users
  resources :affirmations
  resources :comments
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/views/shared/_header.html.erb
<header>
  <nav class="navbar is-warning">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4" style="font-family: cursive;">MyAffirmation</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "アファメーション一覧", affirmations_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "新規投稿", new_affirmation_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "アファメーター一覧", users_path, class: "navbar-item button is-light" %>
              </p>
              <p class="control">
                <%= link_to "マイページ", user_path(current_user), class: "navbar-item button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>

      </div>
    <% else %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "アファメーション一覧", affirmations_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "アファメーター一覧", users_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, class: "button is-warning is-light", method: :post %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </nav>
</header>

app/views/shared/_header_title.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= yield(:title) %>
      </h1>
    </div>
  </div>
</section>