config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :users
  resources :affirmations
  resources :comments
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/affirmation.rb
class Affirmation < ApplicationRecord
  belongs_to :user
  has_many  :comments,  dependent: :destroy
  attachment :image

  with_options presence: true do
    validates :title,     length: { maximum: 30 }
    validates :body,      length: { maximum: 400 }
    validates :image
    validates :user_id
  end

end

app/controllers/affirmations_controller.rb
class AffirmationsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @affirmations = Affirmation.includes(:user).order(id: "DESC").page(params[:page]).per(25)
  end

  def show
    @affirmation = Affirmation.find(params[:id])
  end

  def new
    @affirmation = Affirmation.new
  end

  def create
    @affirmation = current_user.affirmations.build(affirmation_params)
    if @affirmation.save
      redirect_to affirmation_path(@affirmation), notice: '投稿に成功しました。'
    else
      render :new
    end
  end

  def edit
    @affirmation = Affirmation.find(params[:id])
    if @affirmation.user != current_user
      redirect_to affirmations_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @affirmation = Affirmation.find(params[:id])
    if @affirmation.update(affirmation_params)
      redirect_to affirmation_path(@affirmation), notice: '更新に成功しました。'
    else
      render :edit
    end
  end

  def destroy
    affirmation = Affirmation.find(params[:id])
    affirmation.destroy
    redirect_to user_path(affirmation.user)
  end

  private
  def affirmation_params
    params.require(:affirmation).permit(:title, :body, :image)
  end
end

app/helpers/affirmations_helper.rb
module AffirmationsHelper
end

app/views/affirmations/edit.html.erb
<% provide(:title, "アファメーション編集") %>
<%= render 'shared/header_title' %>

<% if @affirmation.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@affirmation.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @affirmation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @affirmation do |f| %>
          <div class="field">
            <%= f.label :title, "アファメーションタイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "宝地図", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/affirmations/index.html.erb
<% provide(:title, "アファメーション一覧") %>
<%= render 'shared/header_title' %>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @affirmations.each do |affirmation| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to affirmation_path(affirmation) do %>
                  <%= attachment_image_tag affirmation, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag affirmation.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to affirmation.user.username, user_path(affirmation.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= affirmation.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/affirmations/new.html.erb
<% provide(:title, "新規アファメーション作成") %>
<%= render 'shared/header_title' %>

<% if @affirmation.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@affirmation.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @affirmation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @affirmation do |f| %>
          <div class="field">
            <%= f.label :title, "アファメーションタイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "宝地図", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/affirmations/show.html.erb
<% provide(:title, "アファメーション詳細") %>
<%= render 'shared/header_title' %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @affirmation, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @affirmation.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>アファメーション</th>
                </tr>
                <tr>
                  <td><%= simple_format @affirmation.body %></td>
                </tr>
              </table>
              <% if @affirmation.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_affirmation_path(@affirmation), class: "button is-success" %>
                <%= link_to "削除", affirmation_path(@affirmation), method: :delete, data: {confirm: "削除しますか？"}, class: "button is-success" %>
              <% end %>
            </div>
            <div class="content">
              <time><%= @affirmation.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @affirmation.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @affirmation.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@affirmation.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @affirmation.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>